//<autogenerated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kuna.Projections.Worker.Kurrent_EF.Example.Migrations
{
    public partial class Init_v2 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CheckPoints",
                columns: table => new
                {
                    ModelName = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    StreamPosition = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CheckPoints", x => x.ModelName);
                });

            migrationBuilder.CreateTable(
                name: "Orders",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Amount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    TaxAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ShippingAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MerchantTransactionFeeAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MerchantTransactionFeePercent = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MerchantTransactionFeePercentCalculated = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    OrderNumber = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ShippingAddress_Line1 = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: true),
                    ShippingAddress_Line2 = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: true),
                    ShippingAddress_City = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ShippingAddress_State = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ShippingAddress_PostCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    ShippingAddress_Country = table.Column<string>(type: "nvarchar(25)", maxLength: 25, nullable: true),
                    BillingAddress_Line1 = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: true),
                    BillingAddress_Line2 = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: true),
                    BillingAddress_City = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    BillingAddress_State = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    BillingAddress_PostCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    BillingAddress_Country = table.Column<string>(type: "nvarchar(25)", maxLength: 25, nullable: true),
                    Customer_FirstName = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: true),
                    Customer_LastName = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: true),
                    Customer_Email = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: true),
                    Customer_PhoneNumber = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    OrderStatus = table.Column<int>(type: "int", nullable: false),
                    CreatedDateTime = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    CompletedDateTime = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    CustomerId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    MerchantId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    TotalFundsCaptured = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    TotalFundsVoided = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    TotalFundsRefunded = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    Source = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: true),
                    MerchantPlatformId = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CurrencyCode = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: true),
                    MerchantReference = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    PaymentAuthorizationId = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CaptureReferences = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    FeeReferences = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    VoidReferences = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    EventNumber = table.Column<long>(type: "bigint", nullable: true),
                    StreamPosition = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: true),
                    HasStreamProcessingFaulted = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Orders", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ProjectionFailures",
                columns: table => new
                {
                    ModelId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ModelName = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    EventNumber = table.Column<long>(type: "bigint", nullable: false),
                    StreamPosition = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: true),
                    FailureCreatedOn = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Exception = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FailureType = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ProjectionFailures", x => new { x.ModelName, x.ModelId });
                });

            migrationBuilder.CreateTable(
                name: "OrderRefunds",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    OrderId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Amount = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: false),
                    RefundId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    MerchantId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    MerchantReference = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    MerchantRefundFeeRebate = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    MerchantRefundFeeRebatePercent = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    MerchantRefundTransactionFee = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    RefundDateTime = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_OrderRefunds", x => x.Id);
                    table.ForeignKey(
                        name: "FK_OrderRefunds_Orders_OrderId",
                        column: x => x.OrderId,
                        principalTable: "Orders",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_OrderRefunds_OrderId",
                table: "OrderRefunds",
                column: "OrderId");

            migrationBuilder.CreateIndex(
                name: "IX_Orders_CustomerId",
                table: "Orders",
                column: "CustomerId");

            migrationBuilder.CreateIndex(
                name: "IX_Orders_EventNumber",
                table: "Orders",
                column: "EventNumber");

            migrationBuilder.CreateIndex(
                name: "IX_Orders_MerchantId",
                table: "Orders",
                column: "MerchantId");

            migrationBuilder.CreateIndex(
                name: "IX_Orders_MerchantPlatformId",
                table: "Orders",
                column: "MerchantPlatformId");

            migrationBuilder.CreateIndex(
                name: "IX_Orders_MerchantReference",
                table: "Orders",
                column: "MerchantReference");

            migrationBuilder.CreateIndex(
                name: "IX_Orders_OrderNumber",
                table: "Orders",
                column: "OrderNumber");

            migrationBuilder.CreateIndex(
                name: "IX_Orders_OrderStatus",
                table: "Orders",
                column: "OrderStatus");

            migrationBuilder.CreateIndex(
                name: "IX_Orders_PaymentAuthorizationId",
                table: "Orders",
                column: "PaymentAuthorizationId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CheckPoints");

            migrationBuilder.DropTable(
                name: "OrderRefunds");

            migrationBuilder.DropTable(
                name: "ProjectionFailures");

            migrationBuilder.DropTable(
                name: "Orders");
        }
    }
}
