// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection;

#nullable disable

namespace Kuna.Projections.Worker.Kurrent_EF.Example.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20220616132112_Init_v2")]
    partial class Init_v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Kuna.Projections.Core.Models.CheckPoint", b =>
                {
                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StreamPosition")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ModelName");

                    b.ToTable("CheckPoints", (string)null);
                });

            modelBuilder.Entity("Kuna.Projections.Core.Models.ProjectionFailure", b =>
                {
                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("EventNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FailureCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreamPosition")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ModelName", "ModelId");

                    b.ToTable("ProjectionFailures", (string)null);
                });

            modelBuilder.Entity("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CaptureReferences")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("CompletedDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("EventNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("FeeReferences")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("HasStreamProcessingFaulted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MerchantPlatformId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MerchantReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("MerchantTransactionFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MerchantTransactionFeePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MerchantTransactionFeePercentCalculated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("PaymentAuthorizationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ShippingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Source")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StreamPosition")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFundsCaptured")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFundsRefunded")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFundsVoided")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VoidReferences")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EventNumber");

                    b.HasIndex("MerchantId");

                    b.HasIndex("MerchantPlatformId");

                    b.HasIndex("MerchantReference");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("OrderStatus");

                    b.HasIndex("PaymentAuthorizationId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MerchantReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MerchantRefundFeeRebate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MerchantRefundFeeRebatePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MerchantRefundTransactionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RefundDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RefundId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderRefunds", (string)null);
                });

            modelBuilder.Entity("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Order", b =>
                {
                    b.OwnsOne("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Customer", "Customer", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("LastName")
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Address", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)");

                            b1.Property<string>("Line1")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.Property<string>("Line2")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.Property<string>("PostCode")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)");

                            b1.Property<string>("Line1")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.Property<string>("Line2")
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)");

                            b1.Property<string>("PostCode")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("BillingAddress");

                    b.Navigation("Customer");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Refund", b =>
                {
                    b.HasOne("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Order", null)
                        .WithMany("OrderRefunds")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Order", b =>
                {
                    b.Navigation("OrderRefunds");
                });
#pragma warning restore 612, 618
        }
    }
}
