// <auto-generated />
using System;
using Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kuna.Projections.Worker.Kurrent_EF.Example.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    partial class OrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kuna.Projections.Abstractions.Models.CheckPoint", b =>
                {
                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GlobalEventPosition")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("ModelName", "InstanceId");

                    b.ToTable("CheckPoints", "dbo");
                });

            modelBuilder.Entity("Kuna.Projections.Abstractions.Models.ProjectionFailure", b =>
                {
                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<string>("InstanceId")
                        .HasColumnType("text");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<long>("EventNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FailureCreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GlobalEventPosition")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("ModelName", "InstanceId", "ModelId");

                    b.ToTable("ProjectionFailures", "dbo");
                });

            modelBuilder.Entity("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CaptureReferences")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("CompletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<long?>("EventNumber")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("FeeReferences")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GlobalEventPosition")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("HasStreamProcessingFaulted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("MerchantPlatformId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MerchantReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("MerchantTransactionFeeAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MerchantTransactionFeePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MerchantTransactionFeePercentCalculated")
                        .HasColumnType("numeric");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentAuthorizationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("ShippingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Source")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFundsCaptured")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFundsRefunded")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFundsVoided")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VoidReferences")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EventNumber");

                    b.HasIndex("MerchantId");

                    b.HasIndex("MerchantPlatformId");

                    b.HasIndex("MerchantReference");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("OrderStatus");

                    b.HasIndex("PaymentAuthorizationId");

                    b.ToTable("Orders", "dbo");
                });

            modelBuilder.Entity("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid");

                    b.Property<string>("MerchantReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("MerchantRefundFeeRebate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MerchantRefundFeeRebatePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MerchantRefundTransactionFee")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RefundDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RefundId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderRefunds", "dbo");
                });

            modelBuilder.Entity("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Order", b =>
                {
                    b.OwnsOne("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Customer", "Customer", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("LastName")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Address", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Country")
                                .HasMaxLength(25)
                                .HasColumnType("character varying(25)");

                            b1.Property<string>("Line1")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("Line2")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("PostCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Country")
                                .HasMaxLength(25)
                                .HasColumnType("character varying(25)");

                            b1.Property<string>("Line1")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("Line2")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)");

                            b1.Property<string>("PostCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("BillingAddress");

                    b.Navigation("Customer");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Refund", b =>
                {
                    b.HasOne("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Order", null)
                        .WithMany("OrderRefunds")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kuna.Projections.Worker.Kurrent_EF.Example.OrdersProjection.Model.Order", b =>
                {
                    b.Navigation("OrderRefunds");
                });
#pragma warning restore 612, 618
        }
    }
}
